insert into User_Rating values ('1')
insert into User_Rating values ('2')
insert into Rating values ('100', 3, '1')
insert into Rating values ('200', 4, '1')
insert into Rating values ('300', 5, '2')
insert into Rating values ('400', 2, '2')